---
permalink: migrate/migrate_to_ng.html 
sidebar: sidebar 
keywords: migrate 
summary: Durante la migrazione dei dati di storage, i backend di storage vengono inseriti manualmente utilizzando le API REST. Durante la migrazione dei dati dei provider VASA, i dati vengono esportati dal database Derby esistente e importati nel database MongoDB. 
---
= Eseguire la migrazione alla versione più recente dei tool ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Durante la migrazione dei dati di storage, i backend di storage vengono inseriti manualmente utilizzando le API REST. Durante la migrazione dei dati dei provider VASA, i dati vengono esportati dal database Derby esistente e importati nel database MongoDB.


NOTE: Si consiglia di eseguire la migrazione della configurazione classica solo se la configurazione è attiva solo la funzione del provider VASA. Se disponi di funzionalità come datastore tradizionali/NVMe, replica vVol e se SRA è abilitato sul classico, non è consigliato migrare l'installazione ai tool ONTAP per VMware vSphere 10,0.

*A proposito di questa attività*

La migrazione è supportata dai tool ONTAP per le release VMware vSphere 9.10D2 e 9.11D4 alla release 10,0. Per migrare da:
* Strumenti ONTAP per VMware vSphere 9,10, prima eseguire l'aggiornamento alla release 9.10D2, quindi eseguire la migrazione alla release 10,0.
* Strumenti ONTAP per VMware vSphere 9,11, prima eseguire l'aggiornamento alla release 9.11D4, quindi eseguire la migrazione alla release 10,0.


NOTE: Come utente esistente, è necessario eseguire il backup OVA da 9,10/9,11 prima di eseguire l'aggiornamento alla patch 9,10D o 9,11D

*Fasi*

. Abilitare la PORTA Derby 1527 sugli strumenti ONTAP esistenti per VMware vSphere 9.10D2 e 9.11D4. Per abilitare la porta, accedere alla CLI con l'utente root ed eseguire il seguente comando:
+
[listing]
----
iptables -I INPUT 1 -p tcp --dport 1527 -j ACCEPT
----
. Distribuzione di OVA per strumenti ONTAP per VMware vSphere 10,0. Vedere link:../deploy/qsg_10.html["ONTAP Tools Avvio rapido"]
. Aggiungi il vCenter che desideri migrare agli strumenti ONTAP per VMware vSphere 10,0. Vedere link:../configure/add_vcenter.html["Aggiungi vCenter"].
. Backend dello storage integrato localmente dalle API vCenter del plug-in remoto. Vedere link:../configure/onboard_svm.html["Back-end dello storage integrato"]. Aggiungi storage come ambito locale per la migrazione.
. Utilizzare la seguente API per migrare:
+
[listing]
----
/api/v1/vcenters/{vcguid}/migration-jobs

{
  "otv_ip": "10.10.10.10",
  "vasa_provider_credentials": {
    "username": "Administrator",
    "password": "password"
  }
}
----
+
Sopra la chiamata API fornisce l'ID lavoro, che può essere utilizzato per il controllo dello stato.

. Utilizzare il seguente URI per controllare lo stato:
+
[listing]
----
https://xx.xx.xx.xxx:8443/virtualization/api/jobmanager/v2/jobs/<JobID>?includeSubJobsAndTasks=true
----
. Una volta completato il processo, convalidare il rapporto di migrazione. È possibile visualizzare il rapporto dalla risposta al lavoro come parte di JobData.
. Aggiungi i tool di ONTAP allo storage provider 10,0 a vCenter e a. link:../configure/register_vasa.html["Registra il provider VASA su vCenter"].
. Arrestare il servizio provider di strumenti ONTAP Storage 9,10 /9,11 VASA Provider (ARRESTARE il provider VASA dalla console principale).
+
NetApp consiglia di non eliminare il provider VASA.

+
Una volta arrestato il vecchio provider VASA, vCenter esegue il failover sui tool ONTAP per VMware vSphere 10,0. Tutti i datastore e le macchine virtuali sono accessibili e vengono serviti dai tool ONTAP per VMware vSphere 10,0.

. Eseguire la migrazione delle patch utilizzando la seguente API:
+
[listing]
----
/virtualization/api/v1/vcenters/{vcguid}/migration-jobs/{migration_id}
----
+
Il corpo della richiesta è vuoto per l'operazione patch.

+

NOTE: uuid è l'uuid di migrazione restituito nella risposta dell'API post-migrazione.

+
Una volta completata con successo l'API di migrazione delle patch, tutte le VM saranno conformi alla policy di storage.



L'API di eliminazione per la migrazione è:

[listing]
----
Delete /virtualization/api/v1/vcenters/{vcguid}/migration-jobs/{migration_id}
----
Questa API elimina la migrazione tramite ID migrazione ed elimina la migrazione sul vCenter specificato.

Dopo aver completato con successo la migrazione e aver registrato gli strumenti ONTAP 10,0 in vCenter, esegui le seguenti operazioni:

* Aggiornare il certificato su tutti gli host.
* Attendere qualche istante prima di eseguire operazioni di DataStore (DS) e Virtual Machine (VM). Il tempo di attesa dipende dal numero di host, DS e VM presenti nell'installazione. Quando non si attende, le operazioni potrebbero non riuscire in modo intermittente.

