---
permalink: concepts/asup.html 
sidebar: sidebar 
keywords:  
summary: 'AutoSupport è un meccanismo che monitora in modo proattivo lo stato di salute del sistema e invia automaticamente messaggi al supporto tecnico NetApp, all"organizzazione di supporto interna e a un partner di supporto. Sebbene i messaggi AutoSupport per il supporto tecnico siano attivati per impostazione predefinita, è necessario impostare le opzioni corrette e disporre di un host di posta valido per l"invio dei messaggi all"organizzazione di supporto interna.' 
---
= AutoSupport
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
AutoSupport è un meccanismo che monitora in modo proattivo lo stato di salute del sistema e invia automaticamente messaggi al supporto tecnico NetApp, all'organizzazione di supporto interna e a un partner di supporto.

AutoSupport è attivato per impostazione predefinita quando si configura il sistema di storage per la prima volta. AutoSupport inizia a inviare messaggi al supporto tecnico 24 ore dopo l'attivazione di AutoSupport.

È possibile attivare o disattivare AutoSupport solo al momento della distribuzione. Si consiglia di lasciarlo attivato. L'abilitazione di AutoSupport può contribuire a velocizzare in modo significativo la determinazione e la risoluzione dei problemi in caso di problemi nel sistema storage. Per impostazione predefinita, il sistema raccoglie le informazioni AutoSupport e le memorizza localmente, anche se si disattiva AutoSupport.
È necessario inserire nella whitelist 216.240.21.18 // support.netapp.com URL nella rete per una corretta trasmissione.
