---
permalink: concepts/concept_vcenter_server_role_based_access_control_features_in_vsc_for_vmware_vsphere.html 
sidebar: sidebar 
keywords:  
summary: 'VCenter Server offre RBAC (role-based access control) che consente di controllare l"accesso agli oggetti vSphere.' 
---
= Panoramica del controllo degli accessi basato sui ruoli negli strumenti ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
VCenter Server offre RBAC (role-based access control) che consente di controllare l'accesso agli oggetti vSphere. VCenter Server fornisce servizi di autenticazione e autorizzazione centralizzati a diversi livelli all'interno del proprio inventario, utilizzando i diritti degli utenti e dei gruppi con ruoli e privilegi. VCenter Server è dotato di cinque componenti principali per la gestione di RBAC:

|===


| Componenti | Descrizione 


| Privilegi | Un privilegio abilita o nega l'accesso per eseguire azioni in vSphere. 


| Ruoli | Un ruolo contiene uno o più privilegi di sistema in cui ogni privilegio definisce un diritto amministrativo per un determinato oggetto o tipo di oggetto nel sistema. Assegnando a un utente un ruolo, l'utente eredita le capacità dei privilegi definiti in quel ruolo. 


| Utenti e gruppi | Gli utenti e i gruppi vengono utilizzati nelle autorizzazioni per assegnare i ruoli da Active Directory (ad) o anche da utenti/gruppi Windows potenzialmente locali (sconsigliato) 


| Permessi | Le autorizzazioni consentono di assegnare privilegi a utenti o gruppi per eseguire determinate azioni e apportare modifiche agli oggetti all'interno di vCenter Server. Le autorizzazioni di vCenter Server interessano solo gli utenti che accedono a vCenter Server anziché gli utenti che accedono direttamente a un host ESXi. 


| Oggetto | Un'entità su cui vengono eseguite le azioni. Gli oggetti VMware vCenter sono data center, cartelle, pool di risorse, cluster, host, e VM 
|===
Per completare correttamente un'attività, è necessario disporre dei ruoli vCenter Server RBAC appropriati. Durante un'attività, gli strumenti ONTAP controllano i ruoli vCenter Server di un utente prima di controllare i privilegi ONTAP dell'utente.


NOTE: I ruoli vCenter Server si applicano agli utenti vCenter degli strumenti ONTAP, non agli amministratori. Per impostazione predefinita, gli amministratori hanno accesso completo al prodotto e non richiedono l'assegnazione di ruoli.

Gli utenti e i gruppi accedono a un ruolo facendo parte di un ruolo vCenter Server.



== Punti chiave sull'assegnazione e la modifica di ruoli per vCenter Server

È necessario impostare i ruoli di vCenter Server solo se si desidera limitare l'accesso a oggetti e task vSphere. In caso contrario, è possibile accedere come amministratore. Questo login consente di accedere automaticamente a tutti gli oggetti vSphere.

Quando si assegna un ruolo, vengono determinate le attività degli strumenti ONTAP che un utente può eseguire. È possibile modificare un ruolo alla volta.
Se si modificano i privilegi all'interno di un ruolo, l'utente associato a tale ruolo dovrebbe disconnettersi e quindi riconnettersi per abilitare il ruolo aggiornato.



== Ruoli standard forniti con gli strumenti ONTAP

Per semplificare le operazioni con i privilegi di vCenter Server e RBAC, gli strumenti ONTAP forniscono ruoli standard degli strumenti ONTAP che consentono di eseguire attività chiave degli strumenti ONTAP. Esiste anche un ruolo di sola lettura che consente di visualizzare le informazioni, ma non di eseguire attività.

È possibile visualizzare i ruoli standard degli strumenti ONTAP facendo clic su *ruoli* nella home page del client vSphere. I ruoli forniti dagli strumenti ONTAP consentono di eseguire le seguenti attività:

|===


| *Ruolo* | *Descrizione* 


| NetApp ONTAP Tools Amministratore | Fornisce tutti i privilegi nativi di vCenter Server e i privilegi specifici degli strumenti ONTAP necessari per eseguire alcune delle attività degli strumenti ONTAP. 


| Strumenti NetApp ONTAP di sola lettura | Fornisce accesso in sola lettura agli strumenti ONTAP. Questi utenti non possono eseguire alcuna azione di ONTAP Tools controllata dall'accesso. 


| Provisioning degli strumenti di NetApp ONTAP  a| 
Fornisce alcuni dei privilegi nativi di vCenter Server e dei privilegi specifici degli strumenti ONTAP necessari per il provisioning dello storage. È possibile eseguire le seguenti operazioni:

* Creare nuovi datastore
* Gestire i datastore


|===
Il ruolo di amministratore dell'interfaccia utente di Manager non è registrato in vCenter. Questo ruolo è specifico dell'interfaccia utente del manager.

Se l'azienda richiede l'implementazione di ruoli più restrittivi rispetto ai ruoli standard degli strumenti ONTAP, è possibile utilizzare i ruoli degli strumenti ONTAP per creare nuovi ruoli.

In questo caso, clonare i ruoli degli strumenti ONTAP necessari e modificare il ruolo clonato in modo che disponga solo dei privilegi richiesti dall'utente.



== Autorizzazioni per backend di storage ONTAP e oggetti vSphere

Se l'autorizzazione vCenter Server è sufficiente, gli strumenti ONTAP controllano i privilegi RBAC di ONTAP (il ruolo ONTAP) associati alle credenziali backend di storage (il nome utente e la password) per determinare se si dispone di privilegi sufficienti per eseguire le operazioni di storage richieste dall'attività degli strumenti ONTAP su quel backend dello storage. Se si dispone dei privilegi ONTAP corretti, è possibile accedere a.
Lo storage termina ed esegue l'attività degli strumenti ONTAP. I ruoli ONTAP determinano le attività degli strumenti ONTAP che puoi eseguire sul backend dello storage.
