---
permalink: manage/update_vcenter_ontap_credentials.html 
sidebar: sidebar 
keywords:  
summary: Puoi aggiornare le credenziali vCenter e ONTAP utilizzando la console di manutenzione. 
---
= Aggiornare le credenziali vCenter e ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puoi aggiornare le credenziali vCenter e ONTAP utilizzando la console di manutenzione.

*Cosa ti serve*

È necessario disporre delle credenziali di accesso utente Maint.

*A proposito di questa attività*

Se sono state modificate le credenziali per vCenter, ONTAP o Datalif dopo la distribuzione, è necessario aggiornare le credenziali utilizzando questa procedura.

*Fasi*

. Dal server vCenter, aprire una console per il provider VASA.
. Accedere come utente di manutenzione.
. Invio `4` Per selezionare Support and Diagnostics (supporto e diagnostica).
. Invio `1` Per selezionare Accedi alla shell diagnostica.
. Invio `y` per procedere.
. Aggiornare le credenziali come richiesto:
+
.. Per aggiornare le credenziali ONTAP, eseguire il comando:
+
--
otv-update --ontapUsername <new username> --ontapPassword <new password>

--
.. Per aggiornare le credenziali vCenter, eseguire il comando:
+
--
otv-update --vcenterUsername <new username> --vcenterPassword <new password>

--
.. Per aggiornare il datalif, eseguire il comando:
+
--
otv-update --dataLif <new Datalif IP>

--



